### ISSUE TITLE
`semgrep` CI job fails

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#1231]
```
Processing sarif files: ["semgrep.sarif"]
  Error: Unexpected end of JSON input
  SyntaxError: Unexpected end of JSON input
      at JSON.parse (<anonymous>)
      at validateSarifFileSchema (/__w/_actions/github/codeql-action/v2/lib/upload-lib.js:192:24)
      at uploadFiles (/__w/_actions/github/codeql-action/v2/lib/upload-lib.js:262:9)
      at Object.uploadFromActions (/__w/_actions/github/codeql-action/v2/lib/upload-lib.js:[14](https://github.com/goblint/analyzer/actions/runs/6710099448/job/18234569783#step:5:15)2:22)
      at async run (/__w/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:50:30)
      at async runWrapper (/__w/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:72:9)
 ```

**Comment by sim642** [comment]
Semgrep fixed it but didn't do a release yet.

**Comment by michael-schwarz** [comment]
Should we manually fix this by pointing to the newest release for now as some others have done? https://github.com/b2network/b2-node/pull/19/files

**Comment by aryx** [comment]
We will update returntocorp/semgrep:latest soon with the fix.
