### ISSUE TITLE
CI: `semgrep` job broken

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#754]
Current runs all fail with

```
Error details: instance additionalProperty "fixes" exists in instance when not allowed
Error: Unable to upload "semgrep.sarif" as it is not valid SARIF:
- instance additionalProperty "fixes" exists in instance when not allowed
Error: Unable to upload "semgrep.sarif" as it is not valid SARIF:
- instance additionalProperty "fixes" exists in instance when not allowed
    at validateSarifFileSchema (/__w/_actions/github/codeql-action/v2/lib/upload-lib.js:203:15)
    at uploadFiles (/__w/_actions/github/codeql-action/v2/lib/upload-lib.js:267:9)
    at Object.uploadFromActions (/__w/_actions/github/codeql-action/v2/lib/upload-lib.js:139:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (/__w/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:52:30)
    at async runWrapper (/__w/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:74:9)
```

**Comment by sim642** [comment]
I've already reported it upstream, we just have to wait until they bother to fix it: https://github.com/returntocorp/semgrep/issues/5421.
